config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Public read-only locations
  resources :locations, only: %i[index show] do
    resources :bookings, only: %i[new create]
    get "availability", to: "bookings#availability"
  end

  resources :regions,
          path: "explore",
          only: %i[index show],
          param: :slug

  # Admin-only full CRUD
  namespace :admin do
    resources :locations
    root to: "locations#index"
    resources :counties
    resources :venues, only: [:index, :show, :update]
    resources :bookings, only: %i[index show update]
  end

  # User favorites
  resources :locations, only: [] do
    resource :favorite, only: [:create, :destroy]
  end

  get "/favorites", to: "favorites#index", as: :favorites

  resources :venues, only: [:new, :create]
  get "list_venue", to: "venues#new"
end

app/views/shared/_admin_navbar.html.erb
<nav class="admin-navbar <%= current_page?("/") ? "" : "not-home" %>" data-controller="navbar">
  <div class="navbar-container">
    <!-- Brand -->
    <div class="navbar-brand-wrapper">
      <%= link_to root_path, class: "navbar-brand" do %>
        Skauter.al
      <% end %>

      <span class="admin-badge">ADMIN</span>
    </div>

    <%# <div class="theme-toggle" data-controller="theme">
      <button class="theme-btn sun" data-action="theme#setDaylight" aria-label="Daylight mode">
        <svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" class="sun">
          <path clip-rule="evenodd" d="M12 1.25C12.4142 1.25 12.75 1.58579 12.75 2V4C12.75 4.41421 12.4142 4.75 12 4.75C11.5858 4.75 11.25 4.41421 11.25 4V2C11.25 1.58579 11.5858 1.25 12 1.25ZM3.66865 3.71609C3.94815 3.41039 4.42255 3.38915 4.72825 3.66865L6.95026 5.70024C7.25596 5.97974 7.2772 6.45413 6.9977 6.75983C6.7182 7.06553 6.2438 7.08677 5.9381 6.80727L3.71609 4.77569C3.41039 4.49619 3.38915 4.02179 3.66865 3.71609ZM20.3314 3.71609C20.6109 4.02179 20.5896 4.49619 20.2839 4.77569L18.0619 6.80727C17.7562 7.08677 17.2818 7.06553 17.0023 6.75983C16.7228 6.45413 16.744 5.97974 17.0497 5.70024L19.2718 3.66865C19.5775 3.38915 20.0518 3.41039 20.3314 3.71609ZM12 7.75C9.65279 7.75 7.75 9.65279 7.75 12C7.75 14.3472 9.65279 16.25 12 16.25C14.3472 16.25 16.25 14.3472 16.25 12C16.25 9.65279 14.3472 7.75 12 7.75ZM6.25 12C6.25 8.82436 8.82436 6.25 12 6.25C15.1756 6.25 17.75 8.82436 17.75 12C17.75 15.1756 15.1756 17.75 12 17.75C8.82436 17.75 6.25 15.1756 6.25 12ZM1.25 12C1.25 11.5858 1.58579 11.25 2 11.25H4C4.41421 11.25 4.75 11.5858 4.75 12C4.75 12.4142 4.41421 12.75 4 12.75H2C1.58579 12.75 1.25 12.4142 1.25 12ZM19.25 12C19.25 11.5858 19.5858 11.25 20 11.25H22C22.4142 11.25 22.75 11.5858 22.75 12C22.75 12.4142 22.4142 12.75 22 12.75H20C19.5858 12.75 19.25 12.4142 19.25 12ZM17.0255 17.0252C17.3184 16.7323 17.7933 16.7323 18.0862 17.0252L20.3082 19.2475C20.6011 19.5404 20.601 20.0153 20.3081 20.3082C20.0152 20.6011 19.5403 20.601 19.2475 20.3081L17.0255 18.0858C16.7326 17.7929 16.7326 17.3181 17.0255 17.0252ZM6.97467 17.0253C7.26756 17.3182 7.26756 17.7931 6.97467 18.086L4.75244 20.3082C4.45955 20.6011 3.98468 20.6011 3.69178 20.3082C3.39889 20.0153 3.39889 19.5404 3.69178 19.2476L5.91401 17.0253C6.2069 16.7324 6.68177 16.7324 6.97467 17.0253ZM12 19.25C12.4142 19.25 12.75 19.5858 12.75 20V22C12.75 22.4142 12.4142 22.75 12 22.75C11.5858 22.75 11.25 22.4142 11.25 22V20C11.25 19.5858 11.5858 19.25 12 19.25Z" />
        </svg>
      </button>

      <button class="theme-btn moon" data-action="theme#setGolden" aria-label="Golden hour mode">
        <svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" class="moon">
          <path d="M21.0672 11.8568L20.4253 11.469L21.0672 11.8568ZM12.1432 2.93276L11.7553 2.29085V2.29085L12.1432 2.93276ZM21.25 12C21.25 17.1086 17.1086 21.25 12 21.25V22.75C17.9371 22.75 22.75 17.9371 22.75 12H21.25ZM12 21.25C6.89137 21.25 2.75 17.1086 2.75 12H1.25C1.25 17.9371 6.06294 22.75 12 22.75V21.25ZM2.75 12C2.75 6.89137 6.89137 2.75 12 2.75V1.25C6.06294 1.25 1.25 6.06294 1.25 12H2.75ZM15.5 14.25C12.3244 14.25 9.75 11.6756 9.75 8.5H8.25C8.25 12.5041 11.4959 15.75 15.5 15.75V14.25ZM20.4253 11.469C19.4172 13.1373 17.5882 14.25 15.5 14.25V15.75C18.1349 15.75 20.4407 14.3439 21.7092 12.2447L20.4253 11.469ZM9.75 8.5C9.75 6.41182 10.8627 4.5828 12.531 3.57467L11.7553 2.29085C9.65609 3.5593 8.25 5.86509 8.25 8.5H9.75ZM12 2.75C11.9115 2.75 11.8077 2.71008 11.7324 2.63168C11.6686 2.56527 11.6538 2.50244 11.6503 2.47703C11.6461 2.44587 11.6482 2.35557 11.7553 2.29085L12.531 3.57467C13.0342 3.27065 13.196 2.71398 13.1368 2.27627C13.0754 1.82126 12.7166 1.25 12 1.25V2.75ZM21.7092 12.2447C21.6444 12.3518 21.5541 12.3539 21.523 12.3497C21.4976 12.3462 21.4347 12.3314 21.3683 12.2676C21.2899 12.1923 21.25 12.0885 21.25 12H22.75C22.75 11.2834 22.1787 10.9246 21.7237 10.8632C21.286 10.804 20.7293 10.9658 20.4253 11.469L21.7092 12.2447Z"/>
        </svg>
      </button>
    </div> %>

    <!-- Links -->
    <nav class="navigation-links">
      <%= link_to "Explore", regions_path, class: "link-navbar" %>
      <%= link_to "Locations", admin_locations_path, class: "link-navbar" %>
      <%= link_to "Counties", admin_counties_path, class: "link-navbar" %>
      <%= link_to "Venues", admin_venues_path, class: "link-navbar" %>
      <%= link_to "Bookings", admin_bookings_path, class: "link-navbar" %>

      <span class="nav-divider"></span>

      <%= link_to "Sign Out",
            destroy_user_session_path,
            data: { turbo_method: :delete },
            class: "link-navbar danger" %>
    </nav>

    <div class="menu-toggle burger" data-slideshow-target="burger">
      <button
        class="menu-icon"
        aria-label="Toggle menu"
        data-slideshow-target="button"
        data-action="click->slideshow#toggle">
        <span class="line"></span>
        <span class="line"></span>
      </button>
    </div>
  </div>
</nav>

app/views/shared/_cta_footer.html.erb
<section class="cta-footer">
  <div class="cta-footer-content">
    <h2>Ready to Start Your Project?</h2>
    <p>
      Browse our collection of Albania’s most spectacular filming locations
    </p>

    <%= link_to "Explore All Locations",
          regions_path,
          class: "cta-footer-button" %>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info fade show m-1" role="alert">
    <%= notice %>
    <a type="button" class="btn-close-alerts" data-bs-dismiss="alert" aria-label="Close">
      x
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning fade show m-1" role="alert">
    <%= alert %>
    <a type="button" class="btn-close-alerts" data-bs-dismiss="alert" aria-label="Close">
      x
    </a>
  </div>
<% end %>

app/views/shared/_locations_form.html.erb
<div class="admin-card">
  <%= form_with model: [:admin, @location], class: "admin-form" do |f| %>

    <div class="form-section">
      <h3>Basic information</h3>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-input", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 4, class: "form-textarea" %>
      </div>
    </div>

    <div class="form-section">
      <h3>Location details</h3>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-input", required: true %>
      </div>

      <div class="form-grid">

        <div class="form-group">
          <%= f.label :location_type, "Location Type" %>
          <%= f.collection_select :location_type,
                Location::LOCATION_TYPES,
                :to_s,
                :to_s,
                { prompt: "Select a location type" },
                class: "form-input", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :county_id, "County" %>
          <%= f.collection_select :county_id,
                County.order(:name),
                :id,
                :name,
                { prompt: "Select a county" },
                class: "form-input", required: true %>
        </div>
      </div>

    </div>

    <div class="form-section">
      <h3>Availability</h3>

      <div>
        <label class="checkbox-item">
          <%= f.check_box :available %>
          <span>Available for booking</span>
        </label>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :capacity, "Maximum capacity (people)" %>
      <%= f.number_field :capacity,
            min: 1,
            step: 1,
            class: "form-input" %>

      <p class="form-hint">
        Maximum number of people allowed on location.
      </p>
    </div>

    <div class="form-section">
      <h3>Pricing</h3>

      <div class="form-grid">
        <div class="form-group">
          <%= f.label :price_per_hour, "Price per hour (ALL)" %>
          <%= f.number_field :price_per_hour,
                min: 0,
                step: 1,
                class: "form-input", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :price_per_day, "Price per day (ALL)" %>
          <%= f.number_field :price_per_day,
                min: 0,
                step: 1,
                class: "form-input", required: true %>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Metadata</h3>

      <div>
        <%= f.label :tags %>
        <div class="tags-grid mt-2">
          <% Location::TAGS.each_slice(5) do |group| %>
            <div class="tags-row">
              <% group.each do |tag| %>
                <label class="checkbox-item">
                  <%= check_box_tag "location[tags][]",
                        tag,
                        @location.tags.include?(tag) %>

                  <span><%= tag.titleize %></span>
                </label>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="mt-5">
        <%= f.label :activity_types, "Activity types" %>
        <div class="tags-grid mt-2">
          <% Location::ACTIVITY_TYPES.each_slice(4) do |group| %>
            <div class="tags-row">
              <% group.each do |activity| %>
                <label class="checkbox-item">
                  <%= check_box_tag "location[activity_types][]",
                        activity,
                        @location.activity_types.include?(activity) %>

                  <span><%= activity %></span>
                </label>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="mt-5">
        <%= f.label :suitable_for, "Suitable for" %>
        <%= f.label :amenities %>
        <%= f.text_field :amenities,
              value: @location.amenities&.join(", "),
              placeholder: "Parking, Electricity, Natural light",
              class: "form-input" %>
        <p class="form-hint">Comma separated</p>
      </div>
    </div>

    <div class="form-section">
      <h3>Images</h3>

      <div class="form-group">
        <%= f.label :cover_image %>
        <%= f.file_field :cover_image, class: "form-file" %>
      </div>

      <div class="form-group">
        <%= f.label :images, "Gallery images" %>
        <%= f.file_field :images, multiple: true, class: "form-file" %>
        <p class="form-hint">Uploading new images will replace the gallery</p>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit class: "admin-button primary" %>
      <%= link_to "Cancel", admin_locations_path, class: "admin-button" %>
    </div>

  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar <%= current_page?("/explore") ? "not-home" : "" %>" data-controller="navbar" data-action="scroll@window->navbar#onScroll" >
  <div class="navbar-container">
    <div>
      <%= link_to "/", class: "navbar-brand" do %>
        Skauter.al
      <% end %>
    </div>

    <%# <div class="theme-toggle" data-controller="theme">
      <button class="theme-btn sun" data-action="theme#setDaylight" aria-label="Daylight mode">
        <svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" class="sun">
          <path clip-rule="evenodd" d="M12 1.25C12.4142 1.25 12.75 1.58579 12.75 2V4C12.75 4.41421 12.4142 4.75 12 4.75C11.5858 4.75 11.25 4.41421 11.25 4V2C11.25 1.58579 11.5858 1.25 12 1.25ZM3.66865 3.71609C3.94815 3.41039 4.42255 3.38915 4.72825 3.66865L6.95026 5.70024C7.25596 5.97974 7.2772 6.45413 6.9977 6.75983C6.7182 7.06553 6.2438 7.08677 5.9381 6.80727L3.71609 4.77569C3.41039 4.49619 3.38915 4.02179 3.66865 3.71609ZM20.3314 3.71609C20.6109 4.02179 20.5896 4.49619 20.2839 4.77569L18.0619 6.80727C17.7562 7.08677 17.2818 7.06553 17.0023 6.75983C16.7228 6.45413 16.744 5.97974 17.0497 5.70024L19.2718 3.66865C19.5775 3.38915 20.0518 3.41039 20.3314 3.71609ZM12 7.75C9.65279 7.75 7.75 9.65279 7.75 12C7.75 14.3472 9.65279 16.25 12 16.25C14.3472 16.25 16.25 14.3472 16.25 12C16.25 9.65279 14.3472 7.75 12 7.75ZM6.25 12C6.25 8.82436 8.82436 6.25 12 6.25C15.1756 6.25 17.75 8.82436 17.75 12C17.75 15.1756 15.1756 17.75 12 17.75C8.82436 17.75 6.25 15.1756 6.25 12ZM1.25 12C1.25 11.5858 1.58579 11.25 2 11.25H4C4.41421 11.25 4.75 11.5858 4.75 12C4.75 12.4142 4.41421 12.75 4 12.75H2C1.58579 12.75 1.25 12.4142 1.25 12ZM19.25 12C19.25 11.5858 19.5858 11.25 20 11.25H22C22.4142 11.25 22.75 11.5858 22.75 12C22.75 12.4142 22.4142 12.75 22 12.75H20C19.5858 12.75 19.25 12.4142 19.25 12ZM17.0255 17.0252C17.3184 16.7323 17.7933 16.7323 18.0862 17.0252L20.3082 19.2475C20.6011 19.5404 20.601 20.0153 20.3081 20.3082C20.0152 20.6011 19.5403 20.601 19.2475 20.3081L17.0255 18.0858C16.7326 17.7929 16.7326 17.3181 17.0255 17.0252ZM6.97467 17.0253C7.26756 17.3182 7.26756 17.7931 6.97467 18.086L4.75244 20.3082C4.45955 20.6011 3.98468 20.6011 3.69178 20.3082C3.39889 20.0153 3.39889 19.5404 3.69178 19.2476L5.91401 17.0253C6.2069 16.7324 6.68177 16.7324 6.97467 17.0253ZM12 19.25C12.4142 19.25 12.75 19.5858 12.75 20V22C12.75 22.4142 12.4142 22.75 12 22.75C11.5858 22.75 11.25 22.4142 11.25 22V20C11.25 19.5858 11.5858 19.25 12 19.25Z" />
        </svg>
      </button>

      <button class="theme-btn moon" data-action="theme#setGolden" aria-label="Golden hour mode">
        <svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" class="moon">
          <path d="M21.0672 11.8568L20.4253 11.469L21.0672 11.8568ZM12.1432 2.93276L11.7553 2.29085V2.29085L12.1432 2.93276ZM21.25 12C21.25 17.1086 17.1086 21.25 12 21.25V22.75C17.9371 22.75 22.75 17.9371 22.75 12H21.25ZM12 21.25C6.89137 21.25 2.75 17.1086 2.75 12H1.25C1.25 17.9371 6.06294 22.75 12 22.75V21.25ZM2.75 12C2.75 6.89137 6.89137 2.75 12 2.75V1.25C6.06294 1.25 1.25 6.06294 1.25 12H2.75ZM15.5 14.25C12.3244 14.25 9.75 11.6756 9.75 8.5H8.25C8.25 12.5041 11.4959 15.75 15.5 15.75V14.25ZM20.4253 11.469C19.4172 13.1373 17.5882 14.25 15.5 14.25V15.75C18.1349 15.75 20.4407 14.3439 21.7092 12.2447L20.4253 11.469ZM9.75 8.5C9.75 6.41182 10.8627 4.5828 12.531 3.57467L11.7553 2.29085C9.65609 3.5593 8.25 5.86509 8.25 8.5H9.75ZM12 2.75C11.9115 2.75 11.8077 2.71008 11.7324 2.63168C11.6686 2.56527 11.6538 2.50244 11.6503 2.47703C11.6461 2.44587 11.6482 2.35557 11.7553 2.29085L12.531 3.57467C13.0342 3.27065 13.196 2.71398 13.1368 2.27627C13.0754 1.82126 12.7166 1.25 12 1.25V2.75ZM21.7092 12.2447C21.6444 12.3518 21.5541 12.3539 21.523 12.3497C21.4976 12.3462 21.4347 12.3314 21.3683 12.2676C21.2899 12.1923 21.25 12.0885 21.25 12H22.75C22.75 11.2834 22.1787 10.9246 21.7237 10.8632C21.286 10.804 20.7293 10.9658 20.4253 11.469L21.7092 12.2447Z"/>
        </svg>
      </button>
    </div> %>

    <nav class="navigation-links">
      <%= link_to "Explore", regions_path, class: "link-navbar" %>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Admin", admin_root_path, class: "link-navbar" %>
      <% else %>
        <%= link_to "List Venue", list_venue_path, class: "link-navbar" %>
      <% end %>


      <% if user_signed_in? && current_user.favorite_locations.any? %>
        <%= link_to "My Favorites", favorites_path, class: "link-navbar" %>
      <% end %>

      <a href="/#hero-search" class="btn btn-navbar btn-gold-shimmer" data-action="click->scroll-to-search#go">
        Get Started
      </a>

      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "link-navbar" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "link-navbar" %>
      <% end %>

    </nav>

    <div class="menu-toggle burger" data-slideshow-target="burger">
      <button
        class="menu-icon"
        aria-label="Toggle menu"
        data-slideshow-target="button"
        data-action="click->slideshow#toggle">
        <span class="line"></span>
        <span class="line"></span>
      </button>
    </div>
  </div>
</nav>